### ISSUE TITLE
wavTranscriber.py IndexError: list index out of range

### ISSUE THREAD

**Issue by vrinda14** [terry-yip/speech-to-text#3]
Hi!
I'm getting the same error.
pb = glob.glob(dirName + "/*.pb")[0]
IndexError: list index out of range

Can yu pls tell how this issue was solved. 
Thanks

**Comment by terry-yip** [comment]
I suppose you met the same issue as this one #1 .Unfortunately I didn't meet the issue on my side, but according to the stack trace described in the referenced issue.
`DEBUG:__main__:Processing speech recognition
Traceback (most recent call last):
  File "speech_to_text.py", line 69, in <module>
    main(sys.argv[1:])
  File "speech_to_text.py", line 35, in main
    output_graph, alphabet, lm, trie = wavTranscriber.resolve_models(model_path)
  File "/home/ivan/PycharmProjects/speech-to-text/wavTranscriber.py", line 77, in resolve_models
    pb = glob.glob(dirName + "/*.pb")[0]
IndexError: list index out of range`
I would guess it might because the deepspeech pretrained model is not in place. 

> As DeepSpeech pre-trained English model is too big to commit to git. You could download from 

> (https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/deepspeech-0.6.1-models.tar.gz)

> Please put the downloaded model files into folder speech-to-text/deepspeech/models
